services:
  anscer-robotics-assignment:
    image: anscer-ros-noetic:dev-latest
    build:
      context: ./docker/dev
      dockerfile: Dockerfile
    container_name: cont-anscer-ros-noetic
    network_mode: "host"
    restart: unless-stopped
    privileged: true
    shm_size: '8g'
    mem_limit: 8g
    runtime: nvidia
    volumes:
      - ../anscer-robotics-assignment:/root/anscer-robotics-assignment:z
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority 
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/root/.Xauthority 
    command: tail -f /dev/null